/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 shop.gltf --transform
Author: Ergoni (https://sketchfab.com/Ergoni)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/juice-carton-shop-537db214710c4968a919a3c40ee6d18f
Title: Juice Carton Shop
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/shop-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[98.05, 23.1, 87.91]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Board001_Tex_1_0.geometry} material={materials.Tex_1} />
          <mesh geometry={nodes.Board001_OutLine_0.geometry} material={materials.OutLine} />
        </group>
        <group position={[97.59, 22.83, 49.63]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Board002_Tex_1_0.geometry} material={materials.Tex_1} />
          <mesh geometry={nodes.Board002_OutLine_0.geometry} material={materials.OutLine} />
        </group>
        <group position={[97.58, 22.29, -1.13]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Board003_Tex_1_0.geometry} material={materials.Tex_1} />
          <mesh geometry={nodes.Board003_OutLine_0.geometry} material={materials.OutLine} />
        </group>
        <group position={[99.84, 23.1, -39.4]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100}>
          <mesh geometry={nodes.Board_Tex_1_0.geometry} material={materials.Tex_1} />
          <mesh geometry={nodes.Board_OutLine_0.geometry} material={materials.OutLine} />
        </group>
        <group position={[-63.42, 1.08, 117.94]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Box001_Tex_1_0.geometry} material={materials.Tex_1} />
          <mesh geometry={nodes.Box001_OutLine_0.geometry} material={materials.OutLine} />
        </group>
        <group position={[-92.84, 1.08, 54.77]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Box002_Tex_1_0.geometry} material={materials.Tex_1} />
          <mesh geometry={nodes.Box002_OutLine_0.geometry} material={materials.OutLine} />
        </group>
        <group position={[-89.36, 26.28, -78.86]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Box003_Tex_1_0.geometry} material={materials.Tex_1} />
          <mesh geometry={nodes.Box003_OutLine_0.geometry} material={materials.OutLine} />
        </group>
        <group position={[-100.27, 0.63, 106.72]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Box_Tex_1_0.geometry} material={materials.Tex_1} />
          <mesh geometry={nodes.Box_OutLine_0.geometry} material={materials.OutLine} />
        </group>
        <group position={[-91.09, 172.83, 39.29]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes['Air-conditioning_Tex_1_0'].geometry} material={materials.Tex_1} />
          <mesh geometry={nodes['Air-conditioning_OutLine_0'].geometry} material={materials.OutLine} />
        </group>
        <group position={[11.83, 0, 98.48]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Pipeline_Tex_1_0.geometry} material={materials.Tex_1} />
          <mesh geometry={nodes.Pipeline_OutLine_0.geometry} material={materials.OutLine} />
        </group>
        <group position={[76.83, 71.25, 21.98]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Can_Tex_1_0.geometry} material={materials.Tex_1} />
          <mesh geometry={nodes.Can_OutLine_0.geometry} material={materials.OutLine} />
        </group>
        <group position={[67.21, 117.72, -43.74]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Juice_Box_Tex_1_0.geometry} material={materials.Tex_1} />
          <mesh geometry={nodes.Juice_Box_OutLine_0.geometry} material={materials.OutLine} />
        </group>
        <group position={[5.86, 105.06, 15.37]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Bottle002_Tex_1_0.geometry} material={materials.Tex_1} />
          <mesh geometry={nodes.Bottle002_OutLine_0.geometry} material={materials.OutLine} />
        </group>
        <group position={[-13.54, 105, -9.04]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Bottle003_Tex_1_0.geometry} material={materials.Tex_1} />
          <mesh geometry={nodes.Bottle003_OutLine_0.geometry} material={materials.OutLine} />
        </group>
        <group position={[5.11, 104.33, -41.78]} rotation={[-Math.PI / 2, 0, 0]} scale={130.04}>
          <mesh geometry={nodes.Bottle004_Tex_1_0.geometry} material={materials.Tex_1} />
          <mesh geometry={nodes.Bottle004_OutLine_0.geometry} material={materials.OutLine} />
        </group>
        <group position={[0.64, 147.33, -9.99]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Bottle005_Tex_1_0.geometry} material={materials.Tex_1} />
          <mesh geometry={nodes.Bottle005_OutLine_0.geometry} material={materials.OutLine} />
        </group>
        <group position={[-13.54, 147.37, 31.8]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Bottle006_Tex_1_0.geometry} material={materials.Tex_1} />
          <mesh geometry={nodes.Bottle006_OutLine_0.geometry} material={materials.OutLine} />
        </group>
        <group position={[-18.41, 147.05, -35.86]} rotation={[-Math.PI / 2, 0, 0]} scale={118.02}>
          <mesh geometry={nodes.Bottle007_Tex_1_0.geometry} material={materials.Tex_1} />
          <mesh geometry={nodes.Bottle007_OutLine_0.geometry} material={materials.OutLine} />
        </group>
        <group position={[5.86, 104.8, 56.15]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Bottle008_Tex_1_0.geometry} material={materials.Tex_1} />
          <mesh geometry={nodes.Bottle008_OutLine_0.geometry} material={materials.OutLine} />
        </group>
        <group position={[-13.54, 105.62, 48.58]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Bottle009_Tex_1_0.geometry} material={materials.Tex_1} />
          <mesh geometry={nodes.Bottle009_OutLine_0.geometry} material={materials.OutLine} />
        </group>
        <group position={[-4.5, 105.62, 32.67]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Bottle010_Tex_1_0.geometry} material={materials.Tex_1} />
          <mesh geometry={nodes.Bottle010_OutLine_0.geometry} material={materials.OutLine} />
        </group>
        <group position={[5.04, 104.23, -16.14]} rotation={[-Math.PI / 2, 0, 0]} scale={99.8}>
          <mesh geometry={nodes.Bottle011_Tex_1_0.geometry} material={materials.Tex_1} />
          <mesh geometry={nodes.Bottle011_OutLine_0.geometry} material={materials.OutLine} />
        </group>
        <group position={[0.62, 147.33, 68.8]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Bottle012_Tex_1_0.geometry} material={materials.Tex_1} />
          <mesh geometry={nodes.Bottle012_OutLine_0.geometry} material={materials.OutLine} />
        </group>
        <group position={[-21.65, 147.33, 54.37]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Bottle001_Tex_1_0.geometry} material={materials.Tex_1} />
          <mesh geometry={nodes.Bottle001_OutLine_0.geometry} material={materials.OutLine} />
        </group>
        <group position={[2.39, 147.37, 20.56]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Bottle013_Tex_1_0.geometry} material={materials.Tex_1} />
          <mesh geometry={nodes.Bottle013_OutLine_0.geometry} material={materials.OutLine} />
        </group>
        <group position={[9.05, 146.82, -49.05]} rotation={[-Math.PI / 2, 0, 0]} scale={84.18}>
          <mesh geometry={nodes.Bottle014_Tex_1_0.geometry} material={materials.Tex_1} />
          <mesh geometry={nodes.Bottle014_OutLine_0.geometry} material={materials.OutLine} />
        </group>
        <group position={[4.57, 146.6, -30.28]} rotation={[-Math.PI / 2, 0, 0]} scale={83.67}>
          <mesh geometry={nodes.Bottle_Tex_1_0.geometry} material={materials.Tex_1} />
          <mesh geometry={nodes.Bottle_OutLine_0.geometry} material={materials.OutLine} />
        </group>
        <group position={[40.06, 65.52, 32.12]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Bony001_Tex_2_0.geometry} material={materials.Tex_2} />
          <mesh geometry={nodes.Bony001_OutLine_0.geometry} material={materials.OutLine} />
        </group>
        <group position={[-100.28, 47.45, 107.13]} rotation={[-Math.PI / 2, -0.03, Math.PI / 2]} scale={100}>
          <mesh geometry={nodes.Bony003_Tex_2_0.geometry} material={materials.Tex_2} />
          <mesh geometry={nodes.Bony003_OutLine_0.geometry} material={materials.OutLine} />
        </group>
        <group position={[16.29, 267.9, 11.32]} rotation={[-1.57, 0, -2.89]} scale={100}>
          <mesh geometry={nodes.Bony007_Tex_2_0.geometry} material={materials.Tex_2} />
          <mesh geometry={nodes.Bony007_OutLine_0.geometry} material={materials.OutLine} />
        </group>
        <group position={[107.66, 236.66, 9.93]} rotation={[3.11, 0, 0]} scale={100}>
          <mesh geometry={nodes.Bony006_Tex_2_0.geometry} material={materials.Tex_2} />
          <mesh geometry={nodes.Bony006_OutLine_0.geometry} material={materials.OutLine} />
        </group>
        <group position={[38.3, 261.82, -57.1]} rotation={[-Math.PI / 2, 0, -0.05]} scale={100}>
          <mesh geometry={nodes.Plant_2_Tex_2_0.geometry} material={materials.Tex_2} />
          <mesh geometry={nodes.Plant_2_OutLine_0.geometry} material={materials.OutLine} />
        </group>
        <group position={[132.07, -3.77, -74.62]} rotation={[-1.53, -0.02, -3.02]} scale={100}>
          <mesh geometry={nodes.Veg_2_Tex_2_0.geometry} material={materials.Tex_2} />
          <mesh geometry={nodes.Veg_2_OutLine_0.geometry} material={materials.OutLine} />
        </group>
        <group position={[63.78, 1.19, -94.24]} rotation={[-0.79, 0.25, 2.82]} scale={100}>
          <mesh geometry={nodes.Veg_3_Tex_2_0.geometry} material={materials.Tex_2} />
          <mesh geometry={nodes.Veg_3_OutLine_0.geometry} material={materials.OutLine} />
        </group>
        <group position={[-69.78, -9.4, 172.51]} rotation={[-1.37, 0.12, -0.01]} scale={100}>
          <mesh geometry={nodes.Veg_1_Tex_2_0.geometry} material={materials.Tex_2} />
          <mesh geometry={nodes.Veg_1_OutLine_0.geometry} material={materials.OutLine} />
        </group>
        <group position={[110.74, 241.73, -64.77]} rotation={[-1.58, 0.2, -1.85]} scale={100}>
          <mesh geometry={nodes.Plant_4_Tex_2_0.geometry} material={materials.Tex_2} />
          <mesh geometry={nodes.Plant_4_OutLine_0.geometry} material={materials.OutLine} />
        </group>
        <group position={[73.75, 39.49, 101.57]} rotation={[-0.86, 0.72, -0.52]} scale={100}>
          <mesh geometry={nodes.Flower001_Tex_2_0.geometry} material={materials.Tex_2} />
          <mesh geometry={nodes.Flower001_OutLine_0.geometry} material={materials.OutLine} />
        </group>
        <group position={[-21.28, 270.59, 28.98]} rotation={[-1.41, 0.25, 0.18]} scale={100}>
          <mesh geometry={nodes.Flower_Tex_2_0.geometry} material={materials.Tex_2} />
          <mesh geometry={nodes.Flower_OutLine_0.geometry} material={materials.OutLine} />
        </group>
        <group position={[60.94, 12.6, 136.93]} rotation={[-1.53, 0.48, 0.11]} scale={100}>
          <mesh geometry={nodes.Flower002_Tex_2_0.geometry} material={materials.Tex_2} />
          <mesh geometry={nodes.Flower002_OutLine_0.geometry} material={materials.OutLine} />
        </group>
        <group position={[56.31, 6.27, 107.63]} rotation={[-Math.PI / 2, 0, -0.07]} scale={100}>
          <mesh geometry={nodes.Plant_3_Tex_2_0.geometry} material={materials.Tex_2} />
          <mesh geometry={nodes.Plant_3_OutLine_0.geometry} material={materials.OutLine} />
        </group>
        <group position={[44.87, 261.61, 6.45]} rotation={[-Math.PI / 2, 0, 0.21]} scale={100}>
          <mesh geometry={nodes.Plant_1_Tex_2_0.geometry} material={materials.Tex_2} />
          <mesh geometry={nodes.Plant_1_OutLine_0.geometry} material={materials.OutLine} />
        </group>
        <group position={[-126.54, 259.3, 138.18]} rotation={[-0.4, 0.75, -1.29]} scale={31.73}>
          <mesh geometry={nodes.Star_Tex_2_0.geometry} material={materials.Tex_2} />
          <mesh geometry={nodes.Star_OutLine_0.geometry} material={materials.OutLine} />
        </group>
        <group position={[58.89, 331.64, -137.88]} rotation={[-0.34, 0.53, -0.83]} scale={21.87}>
          <mesh geometry={nodes.Star001_Tex_2_0.geometry} material={materials.Tex_2} />
          <mesh geometry={nodes.Star001_OutLine_0.geometry} material={materials.OutLine} />
        </group>
        <group position={[130.49, 118.34, -135.63]} rotation={[-0.29, 0.61, -0.88]} scale={18.83}>
          <mesh geometry={nodes.Star002_Tex_2_0.geometry} material={materials.Tex_2} />
          <mesh geometry={nodes.Star002_OutLine_0.geometry} material={materials.OutLine} />
        </group>
        <group position={[-94.69, 380.49, -44.63]} rotation={[-0.3, 1.13, -1.24]} scale={27.9}>
          <mesh geometry={nodes.Star003_Tex_2_0.geometry} material={materials.Tex_2} />
          <mesh geometry={nodes.Star003_OutLine_0.geometry} material={materials.OutLine} />
        </group>
        <mesh geometry={nodes.Leaf_1003_Leafs_Alfa_0.geometry} material={materials.Leafs_Alfa} position={[-113.18, 159.35, 100.19]} rotation={[-1.11, 0.1, 2.84]} scale={[85.43, 72.86, 72.86]} />
        <mesh geometry={nodes.Leaf_1007_Leafs_Alfa_0.geometry} material={materials.Leafs_Alfa} position={[-118.3, 173.82, 90.55]} rotation={[-1.13, 0.89, 1.97]} scale={28.91} />
        <mesh geometry={nodes.Leaf_1008_Leafs_Alfa_0.geometry} material={materials.Leafs_Alfa} position={[-97.4, 149.59, 95.7]} rotation={[-0.64, 0.2, -2.76]} scale={[68.52, 49.05, 47.31]} />
        <mesh geometry={nodes.Leaf_1009_Leafs_Alfa_0.geometry} material={materials.Leafs_Alfa} position={[-107.19, 141.25, 116.67]} rotation={[-0.8, 0.65, -0.17]} scale={[43.03, 45.09, 45.09]} />
        <mesh geometry={nodes.Leaf_1010_Leafs_Alfa_0.geometry} material={materials.Leafs_Alfa} position={[73.61, 194.05, -86.6]} rotation={[-0.52, 0.5, -1.62]} scale={[74.07, 70.92, 70.92]} />
        <mesh geometry={nodes.Leaf_1011_Leafs_Alfa_0.geometry} material={materials.Leafs_Alfa} position={[64.39, 176.17, -81.64]} rotation={[-0.25, 0.51, -2.59]} scale={[47.1, 35.76, 35.76]} />
        <mesh geometry={nodes.Leaf_1012_Leafs_Alfa_0.geometry} material={materials.Leafs_Alfa} position={[88.39, 161.67, -90.15]} rotation={[-0.02, 0.29, -2.39]} scale={[89.42, 83, 79.26]} />
        <mesh geometry={nodes.Leaf_1013_Leafs_Alfa_0.geometry} material={materials.Leafs_Alfa} position={[74.72, 195.3, -76.87]} rotation={[-0.35, 0.43, -2.3]} scale={[48.74, 41.03, 41.03]} />
        <mesh geometry={nodes.Leaf_1014_Leafs_Alfa_0.geometry} material={materials.Leafs_Alfa} position={[65.28, 109.16, -84.15]} rotation={[-0.39, 0.45, -1.2]} scale={[49.1, 45.18, 60.93]} />
        <mesh geometry={nodes.Leaf_1_Leafs_Alfa_0.geometry} material={materials.Leafs_Alfa} position={[55.98, 95.41, -79.01]} rotation={[-0.02, 0.62, -2.34]} scale={[47.1, 35.76, 35.76]} />
      </group>
    </group>
  )
}

useGLTF.preload('/shop-transformed.glb')
